lines = open('c:/mitbtech/Agentic_Ai_projects/ReAssist/streamlit_app.py', encoding='utf-8').read().split('\n')
out = []
for i, line in enumerate(lines):
    if i == 111:
        out.append('    tab1, tab2 = st.tabs(["Research Pipeline", "Observability Dashboard"])')
        out.append('    with tab1:')
        out.append('        ' + line if line else '')
    elif 112 <= i <= 230:
        out.append('        ' + line if line else '')
    elif i == 231:
        out.append('')
        out.append('    with tab2:')
        out.append('        st.header("Pipeline Telemetry & Observability")')
        out.append('        import json, os, glob')
        out.append('        run_files = sorted(glob.glob("logs/runs/run_*.json"), reverse=True)')
        out.append('        runs = []')
        out.append('        for f in run_files[:50]:')
        out.append('            try:')
        out.append('                with open(f) as fp:')
        out.append('                    runs.append(json.load(fp))')
        out.append('            except Exception:')
        out.append('                pass')
        out.append('        if not runs:')
        out.append('            st.info("No observability runs found yet. Run the pipeline to generate telemetry.")')
        out.append('        else:')
        out.append('            total_runs = len(runs)')
        out.append('            avg_time = sum(r.get("total_time_seconds", 0) for r in runs) / total_runs')
        out.append('            avg_papers = sum(r.get("papers_found", 0) for r in runs) / total_runs')
        out.append('            success_count = sum(1 for r in runs if r.get("pipeline_success"))')
        out.append('            success_rate = (success_count / total_runs) * 100')
        out.append('            col1, col2, col3, col4 = st.columns(4)')
        out.append('            col1.metric("Total Runs", total_runs)')
        out.append('            col2.metric("Avg Pipeline Time", f"{avg_time:.1f}s")')
        out.append('            col3.metric("Avg Papers Found", f"{avg_papers:.1f}")')
        out.append('            col4.metric("Success Rate", f"{success_rate:.1f}%")')
        out.append('            st.markdown("---")')
        out.append('            latest_run = runs[0]')
        out.append('            st.subheader(f"Latest Run Agent Timings (ID: {latest_run.get(\\"run_id\\", \\"unknown\\")})")')
        out.append('            if "agent_timings" in latest_run and latest_run["agent_timings"]:')
        out.append('                st.bar_chart(latest_run["agent_timings"])')
        out.append('            else:')
        out.append('                st.info("No detailed timings for latest run.")')
        out.append('            st.markdown("---")')
        out.append('            st.subheader("Recent Executions")')
        out.append('            table_data = []')
        out.append('            for r in runs[:10]:')
        out.append('                q = r.get("query", "")')
        out.append('                q_trunc = q[:47] + "..." if len(q) > 50 else q')
        out.append('                table_data.append({')
        out.append('                    "Run ID": r.get("run_id", ""),')
        out.append('                    "Timestamp": r.get("timestamp", "")[:19].replace("T", " "),')
        out.append('                    "Query": q_trunc,')
        out.append('                    "Total Time (s)": r.get("total_time_seconds", 0),')
        out.append('                    "Papers": r.get("papers_found", 0),')
        out.append('                    "Success": "✅" if r.get("pipeline_success") else "❌"')
        out.append('                })')
        out.append('            st.table(table_data)')
        out.append('            st.markdown("---")')
        out.append('            st.header("AgenticOps Router Statistics")')
        out.append('            try:')
        out.append('                from router import create_router')
        out.append('                router = create_router()')
        out.append('                stats = router.get_stats()')
        out.append('                rcol1, rcol2, rcol3, rcol4 = st.columns(4)')
        out.append('                rcol1.metric("Total Queries Routed", stats.get("total_queries", 0))')
        out.append('                rcol2.metric("Routed to CoT", f"{stats.get("pct_cot", 0)}%")')
        out.append('                rcol3.metric("Routed to Multi-Agent", f"{stats.get("pct_multi_agent", 0)}%")')
        out.append('                rcol4.metric("Total Cost Saved", f"${stats.get("total_cost_saved_usd", 0):.4f}")')
        out.append('            except Exception as e:')
        out.append('                st.error(f"Could not load router stats: {e}")')
        out.append('    ')
        out.append(line)
    else:
        out.append(line)

with open('c:/mitbtech/Agentic_Ai_projects/ReAssist/streamlit_app.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(out))
print("Rewrite complete.")
