"""
ReAssist — Export Service Layer
Generates structured Research Intelligence Dossiers in Markdown, JSON, and BibTeX format.
"""

import json
from typing import Dict, Any
from src.services.storage_service import get_storage_service


class ExportService:
    """Service for compiling and formatting research artifacts and dossiers."""

    def __init__(self):
        self.storage = get_storage_service()

    def generate_bibtex(self, papers: list[dict]) -> str:
        """Convert retrieved academic papers into clean BibTeX citations."""
        entries = []
        for i, paper in enumerate(papers):
            title = paper.get("title", f"Paper {i+1}").replace("{", "").replace("}", "")
            authors = paper.get("authors", ["Unknown"])
            author_str = " and ".join(authors) if isinstance(authors, list) else str(authors)
            year = paper.get("year", "2024")
            cite_key = f"{authors[0].split()[-1] if authors and isinstance(authors, list) else 'Paper'}{year}_{i+1}".lower().replace(" ", "")

            entry = (
                f"@article{{{cite_key},\n"
                f"  title = {{{title}}},\n"
                f"  author = {{{author_str}}},\n"
                f"  year = {{{year}}},\n"
                f"  journal = {{{paper.get('source', 'arXiv / Semantic Scholar')}}},\n"
                f"  url = {{{paper.get('pdf_url', '')}}}\n"
                f"}}"
            )
            entries.append(entry)
        return "\n\n".join(entries)

    def generate_markdown_dossier(self, execution_result: dict, query: str) -> str:
        """Format a full research pipeline execution into a publication-ready Markdown dossier."""
        papers = execution_result.get("papers", [])
        synthesis = execution_result.get("synthesis", "No synthesis available.")
        gaps = execution_result.get("gaps", "No gaps identified.")
        ideas = execution_result.get("ideas", [])
        techniques = execution_result.get("techniques", "No techniques generated.")
        guidance = execution_result.get("guidance", "No guidance generated.")

        lines = [
            f"# Research Intelligence Dossier: {query}",
            "",
            "> Generated by **ReAssist Multi-Agent Intelligence Engine**",
            "",
            "## 1. Executive Synthesis",
            f"{synthesis}",
            "",
            "## 2. Identified Research Gaps",
            f"{gaps}",
            "",
            "## 3. Novel Research Proposals & Hypotheses",
        ]

        if isinstance(ideas, list):
            for idx, idea in enumerate(ideas, 1):
                if isinstance(idea, dict):
                    lines.extend([
                        f"### Proposal {idx}: {idea.get('title', 'Novel Direction')}",
                        f"- **Hypothesis:** {idea.get('hypothesis', 'N/A')}",
                        f"- **Gap Addressed:** {idea.get('gap_addressed', 'N/A')}",
                        f"- **Novelty Justification:** {idea.get('novelty_justification', 'N/A')}",
                        f"- **Feasibility Note:** {idea.get('feasibility_note', 'N/A')}",
                        "",
                    ])
                else:
                    lines.append(f"- {idea}")
        else:
            lines.append(str(ideas))

        lines.extend([
            "## 4. Methodology & Implementation Techniques",
            f"{techniques}",
            "",
            "## 5. Execution Roadmap & Risk Guidance",
            f"{guidance}",
            "",
            "## 6. Literature References & Citations",
        ])

        for idx, paper in enumerate(papers, 1):
            authors = ", ".join(paper.get("authors", [])) if isinstance(paper.get("authors"), list) else str(paper.get("authors", ""))
            lines.append(f"{idx}. **{paper.get('title', 'Unknown')}** ({paper.get('year', 'N/A')}) - {authors}")
            if paper.get("pdf_url"):
                lines.append(f"   - [Link to Paper]({paper.get('pdf_url')})")

        lines.extend([
            "",
            "---",
            "## BibTeX Citations",
            "```bibtex",
            self.generate_bibtex(papers),
            "```"
        ])

        return "\n".join(lines)

    def export_dossier(self, execution_id: str, query: str, execution_result: dict, format: str = "markdown") -> dict:
        """Export dossier in desired format and persist to storage."""
        if format.lower() == "bibtex":
            content = self.generate_bibtex(execution_result.get("papers", []))
            filename = f"exports/{execution_id}_citations.bib"
            content_type = "text/plain"
        elif format.lower() == "json":
            content = json.dumps(execution_result, indent=2, default=str)
            filename = f"exports/{execution_id}_dossier.json"
            content_type = "application/json"
        else:
            content = self.generate_markdown_dossier(execution_result, query)
            filename = f"exports/{execution_id}_dossier.md"
            content_type = "text/markdown"

        storage_ref = self.storage.store_artifact(content, filename, content_type=content_type)
        url = self.storage.get_accessible_url(storage_ref)

        return {
            "execution_id": execution_id,
            "format": format,
            "storage_ref": storage_ref,
            "download_url": url,
            "content": content
        }


_export_service = None

def get_export_service() -> ExportService:
    global _export_service
    if _export_service is None:
        _export_service = ExportService()
    return _export_service
